services:
    demo.headers_security_listener:
        class: DemoBundle\EventListener\AddHeadersListener
        tags:
               - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
